### ISSUE TITLE
При интеграции карты js выдаётся с типом содержимого "текст"

### ISSUE THREAD

**Issue by iozimniy** [and-hom/wwmap#227]
При попытке интеграции карты на страницу браузер возвращает ошибку:

>Access to XMLHttpRequest at 'https://wwmap.ru/map-components/map-html-components->2.1.htm' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' >header is present on the requested resource.

**Comment by and-hom** [comment]
Это отсутствующий в пре-проде файл. Исправлено
