### ISSUE TITLE
Добавить возможность перехода к редактированию другой точки из карты

### ISSUE THREAD

**Issue by gladkovi4** [and-hom/wwmap#233]
При последующем редактировании удобно переключаться между порогами, щелкая по их отметкам на карте
![image](https://user-images.githubusercontent.com/49955650/67107268-cad79e80-f1d4-11e9-8314-42dbbe8e2e61.png)

**Comment by and-hom** [comment]
А что делать, если есть не сохранённые изменения? 
Спрашивать если есть? (это сложно и надо делать)
Спрашивать всегда? (как сейчас при переключениях через дерево)
Сбрасывать изменения?
Сохранять молча?

**Comment by and-hom** [comment]
Стало возможно это сделать благодаря #250
