### ISSUE TITLE
Подумать над табличным-пакетным редактированием

### ISSUE THREAD

**Issue by gladkovi4** [and-hom/wwmap#234]
На мой взгляд редактирование единичных препятствий сейчас сделано удобно. Однако гораздо эффективнее было бы добавлять препятствия пакетно (например, имея на руках готовый отчет).
К примеру подгрузил трек, появилось некоторое подобие таблички-формы, где каждая строка - препятствие, каждый столбец - поле с информацией о нем.

 Аналогичный подход к редактированию уже добавленных препятствий ( в табличном виде) с возможностью добавления-удаления записей и изменения полей.

Речь пока идет только о текстовой информации, фотки и видео это совсем другая история.

**Comment by and-hom** [comment]
Да, надо делать страницу 3 в 1:
1. редактирование таблицей
2. загрузка GPX
3. упорядочивание строчек перетасикванием

**Comment by and-hom** [comment]
Таблица с перетаскиванием строк
https://bootsnipp.com/snippets/P2pn5

**Comment by and-hom** [comment]
Доделать в будущем:
после удаления, если порядок следования был изменён

**Comment by and-hom** [comment]
При большом кол-ве порогов (>50) редактор сильно тормозит. Проблема в показе >50 карт на одной странице. Как первый вариант фикса - показывать карту только по требованию (кнопка "показать карту" вместо карты, по-умолчанию - редактор координат

**Comment by and-hom** [comment]
При загрузке GPX сохранять порядок
