### ISSUE TITLE
Подсветка реки на карте при выделении в списке

### ISSUE THREAD

**Issue by and-hom** [and-hom/wwmap#248]
Скорее всего, добавляем слой с нанесёнными реками

**Comment by and-hom** [comment]
Подсвечивать
1. ~~При выделении в списке~~
2. ~~При нахождении поиском~~
3. При раскрытии кластеризованных порогов

**Comment by iozimniy** [comment]
На данный момент не подсвечиваются:
- Хальмерью
- Кекемерен (ибо это заграница)

**Comment by and-hom** [comment]
Хальмер-ю когда-нибудь потом. Остальное сделано
