### ISSUE TITLE
Проблемы поискового контрола

### ISSUE THREAD

**Issue by iozimniy** [and-hom/wwmap#254]
1. При переходе по поиску с одной реки на другую (или с другой области карты) карта перемещается таким образом, что искомая река находится на краю видимой области. 
Проблема воспроизводится при поиске реки Большой Зеленчук. Начальная позиция: https://wwmap.ru/#65.47467866791541,30.49287080341021,9,osm-standard. пНабрать в строке поиска Большой Зеленчук (Северный Кавказ)) и перейти к нему. Похожая ситуация воспроизводится и при начальной позиции https://wwmap.ru/#50.69296380013919,86.36602775506772,9,osm-standard.

2. Если на видимой на карте области на реке нет порогов, она не отображается в правой панели.

**Comment by and-hom** [comment]
п 2. - пока не делаем:
1. не очень критично
2. не очень понятно, как именно делать
3. нет времени
