### ISSUE TITLE
Не работает поиск по карте

### ISSUE THREAD

**Issue by gladkovi4** [and-hom/wwmap#275]
Не работает поиск по карте яндекса при добавлении препятствий

![image](https://user-images.githubusercontent.com/49955650/72517466-7e980b00-3864-11ea-9c83-e7509f50574e.png)

**Comment by and-hom** [comment]
Теперь api я-карт работает только с ключом.. Получу и добавлю в течении нескольких дней

**Comment by and-hom** [comment]
Добавил токен - работает
