### ISSUE TITLE
Выделение реки на общей карте 

### ISSUE THREAD

**Issue by gladkovi4** [and-hom/wwmap#277]
Не совсем ясно как задается выделение реки на карте
![image](https://user-images.githubusercontent.com/49955650/72527167-30413700-3879-11ea-9633-fffd06e961b0.png)

**Comment by and-hom** [comment]
Треки из базы OpenStreetMap, содержащие пороги с своей окрестности

То есть для реки:
1. Берём все треки из OSM в окрестности порогов
2. Выбираем по назвнию и альтернативным названиям реки

Если трек длинный как на фото, кусок от него не отрезается. То есть, если трек длиннее разумного, он всё равно показан целиком

**Comment by gladkovi4** [comment]
Понял, т.е. показывается условно сплавной участок реки? Просто если бы были места старта/окончания сплава то можно было бы показывать участок между ними (между крайними).

**Comment by and-hom** [comment]
Если бы были - да. 
Цель этой фичи - показать выбранную реку, когда в кадр попало ещё куча всего. 
Например, если кликнуть на Катунь, покажутся ещё Чуя, Урсул и т.д. То есть, надо указать, что из всего на экране относится к Катуни. Края трека действительно никто не прорабатывал

**Comment by and-hom** [comment]
Пока не ясно, как сделать хорошо, и что именно делать. Закрываем
