### ISSUE TITLE
Добавление нового региона

### ISSUE THREAD

**Issue by gladkovi4** [and-hom/wwmap#278]
Не все ключевые регионы есть. Вот например я захотел добавить Забайкалье, или Дальний Восток, что делать.как бытЬ? Пока добавляю в без региона.

**Comment by and-hom** [comment]
Способ один - написать мне, и я добавлю через базу. Это очень редкое действие, и вкладывать, например, 5 человекочасов в то, что будет использовано 2-3 раза не очень хочется.
То есть, сделать это надо, но с приоритетом "в конце очереди"

**Comment by and-hom** [comment]
Добавил форму только для пользователей с ролью ADMIN
