### ISSUE TITLE
Баг при пакетном добавлении препятствия

### ISSUE THREAD

**Issue by gladkovi4** [and-hom/wwmap#279]
Если сначала завести координаты препятствия,а потом выбрать категорию, то координаты сбрасываются.

![image](https://user-images.githubusercontent.com/49955650/72819498-6f5af800-3c7e-11ea-8f54-0781801c7e90.png)
![image](https://user-images.githubusercontent.com/49955650/72819538-80a40480-3c7e-11ea-9d5b-bda6c07f8ed2.png)

**Comment by and-hom** [comment]
Будет исправлено вместе с #250

**Comment by and-hom** [comment]
Fixed
