### ISSUE TITLE
Километраж созданного картой трека

### ISSUE THREAD

**Issue by iozimniy** [and-hom/wwmap#345]
Созданный картой трек при помощи функции "Расстояние по реке" и "Скачать GPX" имеет некорректный километраж с критичной погрешностью. 
Километраж созданного трека проверялся приложениями Google Earth, Offline Maps, SasPlanet и Locus Maps.

[Видео](https://yadi.sk/i/UZmvadIV4dDc4g) создание проблемного трека.
Созданный в нём трек: [track_1.zip](https://github.com/and-hom/wwmap/files/4825911/track_1.zip).

**Comment by and-hom** [comment]
Поисследовал: проблема наблюдается на прямых участках. Когда рисуем по руслу, расстояние сходится
