### ISSUE TITLE
Ссылки на YouTube видео

### ISSUE THREAD

**Issue by gladkovi4** [and-hom/wwmap#374]
Кажется, нет возможности добавлять видео с ссылкой на конкретный тайминг.

Они обычно выглядят так: https://www.youtube.com/watch?v=ZcbJ0W63Yh8&t=120s
Где 120s - означает ссылку на кадр в 120 секунд от начала.

Это нужно для того, чтобы давать ссылки порогов в сагрегированных видосах, когда все пороги в одном ролике.

**Comment by and-hom** [comment]
Дубликат #325
