### ISSUE TITLE
При загрузке вертикальных фоток WWmap переворачивает их

### ISSUE THREAD

**Issue by gladkovi4** [and-hom/wwmap#375]
![image](https://user-images.githubusercontent.com/49955650/101764830-94a06100-3af1-11eb-89b7-264546ed111c.png)
![image](https://user-images.githubusercontent.com/49955650/101764863-a1bd5000-3af1-11eb-9e6e-64992e1d72f8.png)

**Comment by and-hom** [comment]
Даже в браузерной выбиралке эти снимки на боку
![Снимок экрана от 2020-12-13 18-00-31](https://user-images.githubusercontent.com/1333634/102015581-8cecf080-3d6d-11eb-897c-2518d576069d.png)
Это горизонтальное фото с поворотом в exif. Значит делаем поддержку такого поворота
